export const designTokens = {
  color: {
    ink: "#1f2937",
    inkMuted: "#5d6b7c",
    surface: "rgba(255, 255, 255, 0.82)",
    surfaceStrong: "rgba(248, 250, 252, 0.96)",
    surfaceSoft: "rgba(255, 255, 255, 0.68)",
    border: "rgba(120, 139, 163, 0.24)",
    borderStrong: "rgba(120, 139, 163, 0.38)",
    canvasStart: "#f7f1e8",
    canvasEnd: "#edf2f7",
    accent: "#23425d",
    accentHover: "#1b3449",
    accentSoft: "#dbe7f0",
    accentText: "#ffffff",
    success: "#166534",
    warning: "#b45309",
    danger: "#b42318",
    guestCardStart: "#3e63a8",
    guestCardEnd: "#29446f",
    guestCardText: "#ffffff",
    grid: "rgba(148, 163, 184, 0.14)",
    focus: "#2563eb",
  },
  radius: {
    sm: "12px",
    md: "16px",
    lg: "22px",
    xl: "28px",
    pill: "999px",
  },
  shadow: {
    panel: "0 20px 50px rgba(15, 23, 42, 0.08)",
    card: "0 12px 28px rgba(15, 23, 42, 0.08)",
    focus: "0 0 0 3px rgba(37, 99, 235, 0.18)",
  },
  space: {
    xs: "0.4rem",
    sm: "0.6rem",
    md: "0.9rem",
    lg: "1.2rem",
    xl: "1.5rem",
  },
  font: {
    sans: '"Avenir Next", "Inter", "Segoe UI", sans-serif',
  },
} as const;

export function applyThemeTokens(root: HTMLElement = document.documentElement) {
  const entries: Array<[string, string]> = [
    ["--font-sans", designTokens.font.sans],
    ["--color-ink", designTokens.color.ink],
    ["--color-ink-muted", designTokens.color.inkMuted],
    ["--color-surface", designTokens.color.surface],
    ["--color-surface-strong", designTokens.color.surfaceStrong],
    ["--color-surface-soft", designTokens.color.surfaceSoft],
    ["--color-border", designTokens.color.border],
    ["--color-border-strong", designTokens.color.borderStrong],
    ["--color-canvas-start", designTokens.color.canvasStart],
    ["--color-canvas-end", designTokens.color.canvasEnd],
    ["--color-accent", designTokens.color.accent],
    ["--color-accent-hover", designTokens.color.accentHover],
    ["--color-accent-soft", designTokens.color.accentSoft],
    ["--color-accent-text", designTokens.color.accentText],
    ["--color-success", designTokens.color.success],
    ["--color-warning", designTokens.color.warning],
    ["--color-danger", designTokens.color.danger],
    ["--color-guest-card-start", designTokens.color.guestCardStart],
    ["--color-guest-card-end", designTokens.color.guestCardEnd],
    ["--color-guest-card-text", designTokens.color.guestCardText],
    ["--color-grid", designTokens.color.grid],
    ["--color-focus", designTokens.color.focus],
    ["--radius-sm", designTokens.radius.sm],
    ["--radius-md", designTokens.radius.md],
    ["--radius-lg", designTokens.radius.lg],
    ["--radius-xl", designTokens.radius.xl],
    ["--radius-pill", designTokens.radius.pill],
    ["--shadow-panel", designTokens.shadow.panel],
    ["--shadow-card", designTokens.shadow.card],
    ["--shadow-focus", designTokens.shadow.focus],
    ["--space-xs", designTokens.space.xs],
    ["--space-sm", designTokens.space.sm],
    ["--space-md", designTokens.space.md],
    ["--space-lg", designTokens.space.lg],
    ["--space-xl", designTokens.space.xl],
  ];

  for (const [key, value] of entries) {
    root.style.setProperty(key, value);
  }
}
